name: Tests

on:
  push

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [macos-latest]
        width: [1200]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Capture Screensshot
      id: screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/swinton/screenshot-website
        destination: screenshot.png
        full-page: true
        width: ${{ matrix.width }}
