name: My build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/20 * * * *'

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Capture Screensshot
      id: screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://github.com/lisongx/
        destination: screenshot.png
        hideElements: ['signup-prompt', 'header']

  build:
    needs: screenshot
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Download screenshots
      uses: actions/download-artifact@v2
      with:
        name: screenshot
    - name: Display structure of downloaded files
      run: ls -R
    - name: Update README
      env:
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      run: |-
        python update_readme.py
        cat README.md
    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
